apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
        "periodicUpdateInterval": 300,
        "configList": [{
             "resourceName": "shared_hca_rdma",
             "resourcePrefix": "mellanox.com",
             "rdmaHcaMax": 1,
             "selectors": {
               "linkTypes": ["infiniband"]
              }
         }]
    }
# Note: increase rdmaHcaMax to number of pods deployed on each node if greater than 1
